NBODY: 2
FILE_PREFIX: 'PHI_L10_E158_analysis_z100_sigma'

PDG: 333
EINT: 158
MULTIPLICITY: 8.46
BRATIO: 0.489
T: 0.298
EFF: 0.528
SIGMA: 0.003

CENTRALITY_CLASS: 
  - [0, 5]
CT_BINS: [0, 100]
PT_BINS: [0,0.5,1.,1.5,2.,2.5]

BKG_MODELS: ['expo', 'pol1', 'pol2']

BDT_EFFICIENCY: [0.01, 1.00, 0.01] ##min, max ,step

MC_PATH: ../Data/PHI_L10_E158_z100/fntBkg_tof_158_100.root
BKG_PATH: ../Data/PHI_L10_E158_z100/fntBkg_tof_158_100.root
MC_PATH_FULL: ../Data/PHI_L10_E158_z100/fntBkg_tof_158_100.root
DATA_SIG_PATH: ['../Data/PHI_L10_E158_z100/fntBkg_tof_158_100.root']
DATA_BKG_PATH: ['../Data/PHI_L10_E158_z100/fntBkg_tof_158_100.root']
DATA_PATH: ['../Data/PHI_L10_E158_z100/fntBkg_tof_158_100.root']
EVENT_PATH: ['../Data/PHI_L10_E158_z100/Bkg-histos_tof_158_100.root']
EVENT_PATH_FULL: ['../Data/PHI_L10_E158_z100/Bkg-histos_tof_158_100.root']


PRESELECTION: ptMin > 1 and ptMax > 1 and nsigma1 < 3 and nsigma2 < 3 and nsigma1 > -3 and nsigma2 > -3

LARGE_DATA: True
GAUSS: False

XGBOOST_PARAMS:
  # general parameters
  silent: 1 # print message (useful to understand whats happening)
  n_jobs: 8 # number of available threads
  # learning task parameters
  objective: binary:logistic
  random_state: 42
  eval_metric: auc
  tree_method: hist

HYPERPARAMS:
  max_depth: 7
  learning_rate: 0.167
  n_estimators: 83
  gamma: 0.525
  min_child_weight: 9.82
  subsample: 0.89
  colsample_bytree: 0.64
  seed : 42

HYPERPARAMS_RANGE: #TODO: check if it works without tuples
  # booster parameters
  max_depth: !!python/tuple [5, 20] # defines the maximum depth of a single tree (regularization)
  learning_rate: !!python/tuple [0.01, 0.3] # learning rate
  n_estimators: !!python/tuple [50, 500] # number of boosting trees
  gamma: !!python/tuple [0.3, 1.1] # specifies the minimum loss reduction required to make a split
  min_child_weight: !!python/tuple [1, 12]
  subsample: !!python/tuple [0.5, 0.9] # denotes the fraction of observations to be randomly samples for each tree
  colsample_bytree: !!python/tuple [0.5, 0.9] # denotes the fraction of columns to be randomly samples for each tree
  # # lambda: (0,10]  # L2 regularization term on weights
  # # alpha: (0,10]  # L1 regularization term on weight

TRAINING_COLUMNS: 
  - cosp
  - dist
  - nsigma1
  - nsigma2